language: python
python:
  - "3.8"
services:
  - postgresql
install:
  - pip install codecov pytest-cov
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database test_isitdown;' -U postgres
env:
  - ISITDOWN_DATABASE_URI=postgresql://postgres:postgres@127.0.0.1/test_isitdown
  - ISITDOWN_SECRET_KEY=A-secret-key
script:
  - python -m pytest --cov=./
after_success:
  - codecov
