language: python
python:
  - "3.5"
services:
  - postgresql
before_script:
  - psql -c 'create database test_isitdown;' -U postgres
env:
  - DATABASE_URI=postgresql://postgres:postgres@127.0.0.1/test_isitdown
script:
  - python -m pytest
